---
name: Tofu Apply

on:
  push:
    branches:
      - main
      - dev
    paths:
      - tofu/*
  pull_request:
    branches:
      - main
      - dev
    paths:
      - tofu/*

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
        
jobs:
  CD:
    runs-on: ubuntu-slim

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: AWS - Set AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_IAM_GITHUB_OIDC_ROLE_ARN }}
        role-session-name: gh_set_aws_credentials

    - name: AWS - Assume Role
      id: aws_assume_role
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_IAM_ASSUME_ROLE_ARN }}
        role-session-name: github_action
        role-chaining: true

    - name: Setup opentofu  
      uses: opentofu/setup-opentofu@v2
      with:
        tofu_version: 1.6.0

    - name: Plan opentofu
      run: |
        export TF_VAR_aws_region=${{ vars.AWS_REGION }}
        cd tofu
        tofu init -var-file=vars/.vars.tfvars